version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
